[versions]
agp = "8.8.0"
flexbox = "3.0.0"
itext7Core = "7.1.9"
json = "20231013"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
leptonica = "1.83.1-1.5.7"
lifecycleViewmodelKtx = "2.8.7"
lottie = "6.1.0"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
materialVersion = "1.11.0"
roomRuntime = "2.6.1"
tesseract = "5.3.1-1.5.7"
tessTwo = "9.1.0"
tessTwoVersion = "9.1.0"
textRecognition = "16.0.1"
zxingAndroidEmbedded = "4.3.0"

[libraries]
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
itext7-core = { module = "com.itextpdf:itext7-core", version.ref = "itext7Core" }
json = { module = "org.json:json", version.ref = "json" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
leptonica = { module = "org.bytedeco:leptonica", version.ref = "leptonica" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material-v1110 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
rmtheis-tess-two = { module = "com.rmtheis:tess-two", version.ref = "tessTwoVersion" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
tess-two = { module = "com.googlecode.tesseract.android:tess-two", version.ref = "tessTwo" }
tesseract = { module = "org.bytedeco:tesseract", version.ref = "tesseract" }
text-recognition = { module = "com.google.mlkit:text-recognition", version.ref = "textRecognition" }
zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxingAndroidEmbedded" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

